print("Hello Nnenna")
print("Henry")
print("Hello word")
print("Due Date")
print("Animal Kindom class")
print("SOS sign")
print("Gender")
print("Age Limit")
print("Light paint")
print("Glass House")

